# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=26.2
loader_version=0.19.3

# Dependencies
fabric_version=0.152.1+26.2
modmenu_version=20.0.0-beta.2
trinkets_version=3.7.1
cardinal_components_version=6.1.1

#malilib
malilib_version = 670d65c40c

# Mod Properties
mod_version=26.2-1.11.2
maven_group=de.guntram.mcmod
archives_base_name=durabilityviewer

#Modrinth
modrinth_id = WnbN2C6I


