# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=26.3-rc-2
loader_version=0.19.5

# Dependencies
fabric_version=0.160.4+26.3
modmenu_version=21.0.0-beta.1
trinkets_version=3.7.1
cardinal_components_version=6.1.1

#malilib
malilib_version = 670d65c40c

# Mod Properties
mod_version=26.3-1.12.0
maven_group=de.guntram.mcmod
archives_base_name=durabilityviewer

#Modrinth
modrinth_id = WnbN2C6I
