# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=26.1
loader_version=0.18.4

# Dependencies
fabric_version=0.144.0+26.1
modmenu_version=18.0.0-alpha.8
trinkets_version=3.7.1
cardinal_components_version=6.1.1

#malilib
malilib_version = 26.1-0.28.0

# Mod Properties
mod_version=26.1-1.11.2
maven_group=de.guntram.mcmod
archives_base_name=durabilityviewer

#Modrinth
modrinth_id = WnbN2C6I


